import { useState } from "react";
import { PatternHeader } from "../../components/PatternHeader";
import { DemoContainer } from "../../components/DemoContainer";
import { GuidelineSection } from "../../components/GuidelineSection";
import { Bot, CheckCircle2, AlertTriangle, Info, Sparkles } from "lucide-react";

function AIContentLabelingDemo() {
  const [scenario, setScenario] = useState<"social" | "article" | "image">("social");

  return (
    <div className="w-full max-w-lg">
      <div role="tablist" className="flex gap-1 mb-4 p-1 rounded-lg" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
        {(["social", "article", "image"] as const).map(s => (
          <button type="button" role="tab" aria-selected={scenario === s} aria-controls={`tabpanel-${s}`} id={`tab-${s}`} key={s} onClick={() => setScenario(s)} className="flex-1 text-xs py-2 rounded-md font-mono border-none cursor-pointer" style={{ background: scenario === s ? "var(--ai-glow)" : "transparent", color: scenario === s ? "var(--ai-color)" : "var(--text)" }}>
            {s === "social" ? "Social Feed" : s === "article" ? "Article" : "Image/Media"}
          </button>
        ))}
      </div>

      {/* Social media feed with AI labels */}
      {scenario === "social" && (
        <div role="tabpanel" id="tabpanel-social" aria-labelledby="tab-social" className="rounded-2xl overflow-hidden" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
          <div className="px-4 py-3" style={{ borderBottom: "1px solid var(--border)" }}>
            <h3 className="text-sm font-semibold font-mono" style={{ color: "var(--text-bright)" }}>Your Feed</h3>
          </div>

          {/* Human post */}
          <div className="p-4" style={{ borderBottom: "1px solid var(--border)" }}>
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 rounded-full flex items-center justify-center font-bold text-xs" style={{ background: "var(--bg-elevated)", color: "var(--text-bright)" }}>JD</div>
              <div>
                <p className="text-sm font-medium font-mono" style={{ color: "var(--text-bright)" }}>Jane Doe</p>
                <p className="text-xs font-mono" style={{ color: "var(--text-dim)" }}>2 hours ago</p>
              </div>
            </div>
            <p className="text-sm font-mono" style={{ color: "var(--text-bright)" }}>Just finished hiking Mt. Rainier! The view from the summit was incredible.</p>
            <div className="mt-2 rounded-lg h-32 flex items-center justify-center text-xs font-mono" style={{ background: "var(--bg-elevated)", color: "var(--text-dim)" }}>
              [Photo]
            </div>
          </div>

          {/* AI-generated post */}
          <div className="p-4" style={{ background: "rgba(192,132,252,0.05)", borderBottom: "1px solid var(--border)" }}>
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 rounded-full flex items-center justify-center" style={{ background: "rgba(192,132,252,0.15)" }}>
                <Sparkles className="w-4 h-4" style={{ color: "#c084fc" }} />
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium font-mono" style={{ color: "var(--text-bright)" }}>Travel Weekly</p>
                  <span className="text-xs px-1.5 py-0.5 rounded flex items-center gap-1 font-mono" style={{ background: "rgba(192,132,252,0.15)", color: "#c084fc" }}>
                    <Bot className="w-3 h-3" /> AI Generated
                  </span>
                </div>
                <p className="text-xs font-mono" style={{ color: "var(--text-dim)" }}>Sponsored · 1 hour ago</p>
              </div>
            </div>
            <p className="text-sm font-mono" style={{ color: "var(--text-bright)" }}>10 hidden hiking gems near Seattle that locals don't want you to know about! Number 7 will blow your mind.</p>
            <div className="mt-2 rounded-lg h-32 flex items-center justify-center relative" style={{ background: "var(--bg-elevated)" }}>
              <span className="text-xs font-mono" style={{ color: "var(--text-dim)" }}>[AI-Generated Image]</span>
              <span className="absolute bottom-2 right-2 text-xs text-white px-2 py-0.5 rounded flex items-center gap-1 font-mono" style={{ background: "rgba(192,132,252,0.8)" }}>
                <Sparkles className="w-3 h-3" /> AI Generated
              </span>
            </div>
            <div className="mt-2 flex items-center gap-1 text-xs font-mono" style={{ color: "#c084fc" }}>
              <Info className="w-3 h-3" />
              This post and image were generated by AI. <a href="#" onClick={e => e.preventDefault()} className="underline" style={{ color: "#c084fc" }}>Why am I seeing this?</a>
            </div>
          </div>

          {/* AI-assisted post */}
          <div className="p-4">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 rounded-full flex items-center justify-center font-bold text-xs" style={{ background: "var(--bg-elevated)", color: "var(--text-bright)" }}>MK</div>
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium font-mono" style={{ color: "var(--text-bright)" }}>Mark Kim</p>
                  <span className="text-xs px-1.5 py-0.5 rounded flex items-center gap-1 font-mono" style={{ background: "rgba(192,132,252,0.1)", color: "var(--ai-color)" }}>
                    <Sparkles className="w-3 h-3" /> AI Assisted
                  </span>
                </div>
                <p className="text-xs font-mono" style={{ color: "var(--text-dim)" }}>30 min ago</p>
              </div>
            </div>
            <p className="text-sm font-mono" style={{ color: "var(--text-bright)" }}>Here's my summary of the Q4 earnings call...</p>
            <div className="mt-2 rounded-lg p-3 text-xs font-mono" style={{ background: "rgba(192,132,252,0.05)", border: "1px solid rgba(192,132,252,0.15)", color: "var(--text)" }}>
              <strong style={{ color: "var(--ai-color)" }}>AI-assisted content:</strong> This post was written by a human with AI writing assistance. The ideas are the author's; the wording was refined by AI.
            </div>
          </div>
        </div>
      )}

      {/* Article with AI labeling */}
      {scenario === "article" && (
        <div role="tabpanel" id="tabpanel-article" aria-labelledby="tab-article" className="rounded-2xl p-6" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
          {/* AI-generated article */}
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-xs px-2 py-1 rounded-full flex items-center gap-1 font-medium font-mono" style={{ background: "rgba(192,132,252,0.15)", color: "#c084fc" }}>
                <Bot className="w-3.5 h-3.5" /> AI-Generated Article
              </span>
            </div>
            <h2 className="text-lg font-bold font-mono mb-2" style={{ color: "var(--text-bright)" }}>The Future of Remote Work: 5 Trends for 2026</h2>
            <p className="text-sm font-mono mb-3" style={{ color: "var(--text)" }}>This article was generated by an AI language model and reviewed by an editor.</p>
            <div className="space-y-2 text-sm font-mono" style={{ color: "var(--text-bright)" }}>
              <p>The landscape of remote work continues to evolve...</p>
              <p>[Article content...]</p>
            </div>

            <div className="mt-4 pt-4" style={{ borderTop: "1px solid var(--border)" }}>
              <div className="rounded-lg p-3" style={{ background: "rgba(192,132,252,0.08)", border: "1px solid rgba(192,132,252,0.2)" }}>
                <h4 className="text-xs font-semibold font-mono mb-2 flex items-center gap-1" style={{ color: "#c084fc" }}>
                  <Info className="w-3.5 h-3.5" /> Transparency notice
                </h4>
                <ul className="text-xs font-mono space-y-1" style={{ color: "var(--text)" }}>
                  <li><strong style={{ color: "var(--text-bright)" }}>Generated by:</strong> Large language model (AI)</li>
                  <li><strong style={{ color: "var(--text-bright)" }}>Reviewed by:</strong> Human editor (fact-checked key claims)</li>
                  <li><strong style={{ color: "var(--text-bright)" }}>Training data:</strong> Web content up to January 2026</li>
                  <li><strong style={{ color: "var(--text-bright)" }}>Limitations:</strong> May contain inaccuracies or outdated information</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="rounded-lg p-3 text-xs font-mono" style={{ background: "var(--ai-glow)", border: "1px solid var(--ai-border)", color: "var(--ai-color)" }}>
            <strong>EU AI Act Art. 50(4):</strong> <span style={{ color: "var(--text)" }}>AI-generated text published to inform the public on matters of public interest must be labeled as AI-generated, unless the content has been subjected to human review and a natural person holds editorial responsibility.</span>
          </div>
        </div>
      )}

      {/* AI-generated image labeling */}
      {scenario === "image" && (
        <div role="tabpanel" id="tabpanel-image" aria-labelledby="tab-image" className="rounded-2xl p-6" style={{ background: "var(--bg-card)", border: "1px solid var(--border)" }}>
          <h3 className="font-bold font-mono text-sm mb-4" style={{ color: "var(--text-bright)" }}>Content authenticity signals</h3>

          <div className="space-y-4">
            {/* Real photo */}
            <div className="rounded-lg overflow-hidden" style={{ border: "1px solid var(--green-border)" }}>
              <div className="h-32 flex items-center justify-center text-xs font-mono relative" style={{ background: "rgba(0,255,65,0.05)", color: "var(--text-dim)" }}>
                [Real photograph]
                <span className="absolute bottom-2 left-2 text-xs px-2 py-0.5 rounded flex items-center gap-1 font-mono" style={{ background: "rgba(0,255,65,0.8)", color: "var(--bg)" }}>
                  <CheckCircle2 className="w-3 h-3" /> Authentic
                </span>
              </div>
              <div className="p-3">
                <p className="text-xs font-mono flex items-center gap-1" style={{ color: "var(--green)" }}><CheckCircle2 className="w-3.5 h-3.5" /> Original photograph — camera metadata verified</p>
                <p className="text-xs font-mono mt-1" style={{ color: "var(--text-dim)" }}>Canon EOS R5 · ISO 200 · f/8 · 1/250s · No AI modifications detected</p>
              </div>
            </div>

            {/* AI-generated image */}
            <div className="rounded-lg overflow-hidden" style={{ border: "1px solid rgba(192,132,252,0.3)" }}>
              <div className="h-32 flex items-center justify-center text-xs font-mono relative" style={{ background: "rgba(192,132,252,0.1)", color: "var(--text-dim)" }}>
                [AI-generated image]
                <span className="absolute bottom-2 left-2 text-xs text-white px-2 py-0.5 rounded flex items-center gap-1 font-mono" style={{ background: "rgba(192,132,252,0.8)" }}>
                  <Sparkles className="w-3 h-3" /> AI Generated
                </span>
              </div>
              <div className="p-3">
                <p className="text-xs font-mono flex items-center gap-1" style={{ color: "#c084fc" }}><Sparkles className="w-3.5 h-3.5" /> AI-generated image</p>
                <p className="text-xs font-mono mt-1" style={{ color: "var(--text-dim)" }}>Model: DALL-E 3 · C2PA watermark embedded · Generated March 2026</p>
              </div>
            </div>

            {/* AI-modified image */}
            <div className="rounded-lg overflow-hidden" style={{ border: "1px solid rgba(255,170,0,0.3)" }}>
              <div className="h-32 flex items-center justify-center text-xs font-mono relative" style={{ background: "rgba(255,170,0,0.1)", color: "var(--text-dim)" }}>
                [AI-modified photograph]
                <span className="absolute bottom-2 left-2 text-xs px-2 py-0.5 rounded flex items-center gap-1 font-mono" style={{ background: "var(--amber)", color: "var(--bg)" }}>
                  <AlertTriangle className="w-3 h-3" /> AI Modified
                </span>
              </div>
              <div className="p-3">
                <p className="text-xs font-mono flex items-center gap-1" style={{ color: "var(--amber)" }}><AlertTriangle className="w-3.5 h-3.5" /> Original photo with AI modifications</p>
                <p className="text-xs font-mono mt-1" style={{ color: "var(--text-dim)" }}>Background replaced by AI · Subject face untouched · Modification map available</p>
              </div>
            </div>
          </div>

          <div className="rounded-lg p-3 mt-4 text-xs font-mono" style={{ background: "var(--ai-glow)", border: "1px solid var(--ai-border)", color: "var(--ai-color)" }}>
            <strong>C2PA Standard:</strong> <span style={{ color: "var(--text)" }}>The Coalition for Content Provenance and Authenticity provides machine-readable metadata for content authenticity. EU AI Act Art. 50(2) requires AI-generated content to be marked in machine-readable format.</span>
          </div>
        </div>
      )}
    </div>
  );
}

export function AIContentLabelingPattern() {
  return (
    <div>
      <PatternHeader
        title="AI Content Labeling"
        description="How to label AI-generated and AI-modified content — social media feeds, articles, images. Covers EU AI Act Article 50 requirements including machine-readable watermarking."
        severity="critical"
        tags={["EU AI Act Art. 50", "C2PA", "Content Authenticity"]}
      />

      <DemoContainer label="AI content labeling (3 variants)">
        <AIContentLabelingDemo />
      </DemoContainer>

      <GuidelineSection
        dos={[
          "Label AI-generated content with a visible badge (text + icon) at the point of display",
          "Distinguish between: fully AI-generated, AI-assisted, and AI-modified content",
          "Embed machine-readable watermarks (C2PA standard) for programmatic detection",
          "Show content provenance: what model, when generated, whether human-reviewed",
          "Provide a 'Why am I seeing this?' link for AI-generated content in feeds",
          "Label AI-generated images both visually (overlay badge) and in metadata",
          "Show a transparency notice on AI-generated articles with limitations stated",
        ]}
        donts={[
          "Don't publish AI-generated text on public interest topics without disclosure (Art. 50(4))",
          "Don't use AI-generated images without visible and machine-readable labeling (Art. 50(2))",
          "Don't remove AI watermarks or metadata from content you redistribute",
          "Don't label AI-assisted content the same as fully AI-generated content — there's a difference",
          "Don't hide AI labels behind clicks or tooltips — they must be immediately visible",
          "Don't present AI-generated content as photojournalism without explicit disclosure",
          "Don't use AI deepfakes without disclosure — this is specifically called out in Art. 50(3)",
        ]}
        securityRationale="EU AI Act Article 50(2)-(4) requires providers to mark AI-generated content in machine-readable format and ensure detectable watermarking. Article 50(4) specifically addresses AI-generated text published to inform the public — it must be labeled unless human-reviewed. The C2PA (Coalition for Content Provenance and Authenticity) standard, backed by Adobe, Microsoft, and BBC, provides the technical framework. Non-compliance faces fines up to 15M EUR. Deadline: August 2026."
        accessibilityNotes={[
          "AI labels must be in text, not just icons — screen readers can't interpret icon-only labels",
          "Overlay badges on images need sufficient contrast against varied backgrounds",
          "Provenance information should be available in alt text or longdesc",
          "Machine-readable metadata (C2PA) supplements but doesn't replace visible labels",
          "Color coding (purple for AI, green for authentic) must be paired with text labels",
        ]}
      />
    </div>
  );
}
